language: cpp
dist: bionic
compiler:
  - clang
  - gcc
# sudo: false
# addons:
#   apt:
#     packages:
#     - cmake
#     - gfortran
before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install cmake gfortran
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
notifications:
  email: false
