language: cpp
compiler:
  - gcc
# sudo: false
# addons:
#   apt:
#     packages:
#     - cmake
#     - gfortran
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update --quiet
  - sudo apt-get install cmake gfortran
  - sudo apt-get install -y g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
notifications:
  email: false
